version: '3'
services:

  php:
    build:
      context: ./images
      dockerfile: php.docker
    container_name: php
    user: ${CURRENT_UID}
    restart: always
    volumes:
      - '../src/:/code/'
      - './config/php/php.ini-production:/usr/local/etc/php/php.ini'
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"

  mysql:
    image: mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - "./data/db:/var/lib/mysql"

  webserver:
    image: 'nginx:latest'
    user: ${CURRENT_UID}
    depends_on:
    - php
    restart: always
    ports:
      - "80:8000"
    volumes:
      - '../src/:/code'
      - './config/nginx/nginx_default_site.conf:/etc/nginx/conf.d/default.conf'
      - './config/nginx/nginx.conf:/etc/nginx/nginx.conf'
